server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///myactiviti?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配 第一次设置为true 会自动创建表结构，之后即可设置为false 提高运行速度