server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///myactiviti?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver